# Generated by Django 3.0.2 on 2021-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('mobilenum', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=400)),
                ('amount', models.CharField(max_length=100)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
