# Generated by Django 3.0.2 on 2021-02-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210217_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
