# Generated by Django 3.0.2 on 2021-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
