# Generated by Django 3.0.2 on 2021-02-19 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210219_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mobilenum',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
